import type { WorldRuntime } from './runtime.ts';

/** References are generated by this application and never accepted from the browser. */
export interface CheckpointAdapter {
  capture(world: WorldRuntime, reference: string): Promise<void>;
  restore(reference: string, id: string): Promise<WorldRuntime>;
  remove(reference: string): Promise<void>;
  collect?(references: string[]): Promise<string[]>;
}
type IndexedSnapshot = { id: string; digest: string; parentDigest: string | null; group: string | null; name: string | null; reference: string };
/** Delete only requested leaves. Ancestors of retained snapshots remain queued. */
export async function collectCheckpointSnapshots(references: string[], inventory: IndexedSnapshot[], remove: (reference: string) => Promise<void>): Promise<string[]> {
  const existing = [...inventory];
  const pending = new Set(references), removed: string[] = [];
  let progressed = true;
  while (progressed) {
    progressed = false;
    for (const reference of pending) {
      const [group, member] = reference.split(':');
      const snapshot = existing.find(s => s.group === group && s.name === member);
      if (snapshot) {
        if (existing.some(child => child.parentDigest === snapshot.id || child.parentDigest === snapshot.digest)) continue;
        // Use the exact indexed artifact, and keep the SDK's child guard enabled.
        await remove(snapshot.reference);
        existing.splice(existing.indexOf(snapshot), 1);
      }
      removed.push(reference); pending.delete(reference); progressed = true;
    }
  }
  return removed;
}
export const checkpoints: CheckpointAdapter = {
  async capture(world, reference) {
    if (!world.captureCheckpoint) throw new Error('Runtime does not support execution checkpoints');
    await world.captureCheckpoint(reference);
  },
  async restore(reference, id) {
    const { restoreCheckpoint } = await import('./runtime.ts');
    return restoreCheckpoint(reference, id);
  },
  async collect(references) {
    const { Snapshot } = await import('microsandbox');
    return collectCheckpointSnapshots(references, await Snapshot.list(), reference => Snapshot.remove(reference));
  },
  async remove(reference) {
    const { Snapshot } = await import('microsandbox');
    // Absence makes cleanup idempotent; other failures must remain visible.
    const existing = await Snapshot.list();
    const [group, member] = reference.split(':');
    const match = existing.find(s => s.group === group && s.name === member);
    if (match) await Snapshot.remove(reference);
  },
};
