import './runtime-env.ts';
import './build-bridge.ts';
import assert from 'node:assert/strict';
import { Session } from '../examples/doom/server/src/session.ts';
import { Recordings } from '../examples/doom/server/src/recordings.ts';
import { SessionStore } from '../examples/doom/server/src/persistence.ts';
import { checkpoints } from '../examples/doom/server/src/checkpoints.ts';
import { navigateDoomInputs } from '../examples/doom/server/src/doom-navigation.ts';
import { geometryFor } from '../examples/doom/server/src/doom-geometry.ts';
import { Jev } from '../examples/doom/server/src/jev.ts';
import { createWorld, reconnectWorld, recoverPendingWorld, destroyWorld } from '../examples/doom/server/src/runtime.ts';
const store = new SessionStore('.cache/session-smoke.json');
const session = new Session(new Jev(), { threshold: 0.75, horizon: 105, branches: 2, paceMs: 0 });
session.setControls(async (state, inputs, navigation, policy) => navigateDoomInputs(state, inputs, await geometryFor(state, true, true), navigation, policy));
session.setCheckpointAdapter(checkpoints);
const recordings = new Recordings('.cache/session-smoke-recordings');
await recordings.open();
session.setRecorder((world, frame) => recordings.record(world, frame));
session.setMainRecorder(id => recordings.retainPath(id));
if (process.argv[2] === 'create') {
  await session.initialize(await createWorld(`mom-session-smoke-${Date.now()}`));
  session.setTrialDuration(70);
  session.saveSkill({ name: 'Conserve ammunition', instructions: 'Fire only when an enemy is aligned and not behind a wall.', enabled: true });
  session.useExperience(true);
  session.setPersistence(c => store.save(c));
  session.queueObjective('Stay alive and avoid damage.');
  session.step(); await session.idle();
  assert.equal(session.snapshot().error, undefined);
  assert.equal(session.snapshot().stage, 'choosing');
  assert.equal(session.snapshot().decision?.kind, 'plan');
  assert.equal(session.snapshot().decision?.evidence?.skills?.[0]?.name, 'Conserve ammunition');
  assert.ok(session.snapshot().worlds.some(w => w.plan));
  await store.save(session.checkpoint()); await store.flush();
  await recordings.flush();
  console.log('Saved full session with real Jev decision and two detached experiments.');
  process.exit(0);
} else {
  const saved = await store.load(); assert.ok(saved);
  await session.restore(saved, reconnectWorld, recoverPendingWorld, destroyWorld);
  session.setPersistence(c => store.save(c));
  try {
    const restored = session.snapshot();
    for (const before of saved.worlds) assert.deepEqual(restored.worlds.find(w => w.id === before.view.id)!.state, before.view.state);
    assert.equal(restored.running, false);
    for (const before of saved.worlds) assert.deepEqual(session.checkpoint().worlds.find(w => w.view.id === before.view.id)!.navigation, before.navigation);
    for (const before of saved.worlds) assert.deepEqual(session.checkpoint().worlds.find(w => w.view.id === before.view.id)!.plan, before.plan);
    assert.equal(restored.trialDurationTicks, 70);
    assert.equal(restored.experience?.enabled, true);
    assert.ok(restored.experience!.stored > 0);
    assert.deepEqual(session.checkpoint().experience, saved.experience);
    assert.equal(restored.objective, 'Stay alive and avoid damage.');
    assert.deepEqual(restored.skills, saved.view.skills);
    session.step(); await session.idle();
    assert.equal(session.snapshot().worlds.filter(w => w.role === 'main').length, 1);
    const id = session.snapshot().mainId;
    const checkpointState = structuredClone(session.snapshot().worlds.find(world => world.id === id)!.state);
    const checkpointStats = structuredClone(session.snapshot().stats!);
    const checkpointFrame = Buffer.from(session.frame(id));
    await session.saveRecoveryCheckpoint();
    const checkpointId = session.snapshot().recovery!.checkpoints.at(-1)!.id;
    await session.takeover(id); await session.input(id, ['forward']); session.release(id);
    assert.equal(session.snapshot().worlds.find(w => w.id === id)!.state.tick, 112);
    await recordings.flush();
    const recording = recordings.list().worlds.find(w => w.id === id)!;
    assert.ok(recording.frames > 10);
    assert.equal((await recordings.get(id, 0)).world.state.tick, 35);
    assert.equal((await recordings.get(id, recording.frames - 1)).world.state.tick, 112);
    const path = await recordings.path(id, 112);
    assert.equal(path.missingHistory, false);
    assert.equal(path.segments.length, 2);
    assert.deepEqual(path.segments.flatMap(segment => segment.ticks), [...Array.from({ length: 71 }, (_, i) => 35 + i), 112]);
    assert.ok(recordings.list().worlds.find(world => world.id === id)!.selected);
    await session.rollback(checkpointId);
    const restoredId = session.snapshot().mainId;
    assert.notEqual(restoredId, id);
    assert.deepEqual(session.snapshot().worlds.find(world => world.id === restoredId)!.state, checkpointState);
    assert.deepEqual(session.frame(restoredId), checkpointFrame);
    assert.equal(session.snapshot().stats!.kills, checkpointStats.kills);
    assert.equal(session.snapshot().stats!.seconds, checkpointStats.seconds);
    assert.equal(session.snapshot().stats!.attempts.rollbacks, 1);
    await recordings.flush();
    const restoredPath = await recordings.path(restoredId, checkpointState.tick);
    assert.equal(restoredPath.missingHistory, false);
    assert.equal(restoredPath.lastTick, checkpointState.tick);
    assert.deepEqual(restoredPath.segments.flatMap(segment => segment.ticks), Array.from({ length: 71 }, (_, i) => 35 + i));
    console.log('PASS: execution checkpoint restored exact state and frame; selected replay excludes the abandoned continuation.');
    await session.restart(() => createWorld(`mom-restart-smoke-${Date.now()}`), root => recordings.clearExcept(root));
    const fresh = session.snapshot();
    assert.equal(fresh.worlds.length, 1); assert.equal(fresh.worlds[0]!.generation, 0);
    assert.equal(fresh.worlds[0]!.state.tick, 35); assert.equal(fresh.worlds[0]!.state.health, 100);
    assert.deepEqual(fresh.skills, saved.view.skills);
    assert.equal(fresh.experience!.stored, 0); assert.equal(fresh.running, false);
    assert.deepEqual(recordings.list().worlds.map(world => world.id), [fresh.mainId]);
    console.log('PASS: stitched the selected path and restarted into a fresh VM, clearing only smoke recordings.');
    console.log('PASS: session survived host exit, promoted one winner, then accepted human control.');
  } finally { await session.close(); }
}
