import { createHash } from 'node:crypto';
import { mkdir, writeFile, rename } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
const platform = process.platform === 'darwin' ? 'darwin' : process.platform === 'linux' ? 'linux' : undefined;
const arch = process.arch === 'arm64' ? 'aarch64' : process.arch === 'x64' ? 'x86_64' : undefined;
if (!platform || !arch || platform === 'darwin' && arch !== 'aarch64') throw new Error('Automatic runtime setup supports Apple Silicon macOS and Linux arm64/x64');
const name = `microsandbox-${platform}-${arch}.tar.gz`;
const base = 'https://github.com/superradcompany/microsandbox/releases/download/v0.7.1';
const download = async (url: string) => { const r = await fetch(url); if (!r.ok) throw new Error(`Download failed: HTTP ${r.status}`); return Buffer.from(await r.arrayBuffer()); };
const checksums = (await download(`${base}/checksums.sha256`)).toString();
const digest = checksums.split('\n').find(line => line.endsWith(`  ${name}`))?.split(' ')[0];
if (!digest) throw new Error('Release checksum missing');
const archive = await download(`${base}/${name}`);
if (createHash('sha256').update(archive).digest('hex') !== digest) throw new Error('Runtime checksum mismatch');
await mkdir('.cache', { recursive: true }); await mkdir('.runtime/bin', { recursive: true }); await mkdir('.runtime/lib', { recursive: true });
await writeFile('.cache/runtime.tar.gz', archive);
const entries = execFileSync('tar', ['-tzf', '.cache/runtime.tar.gz'], { encoding: 'utf8' }).trim().split('\n');
const lib = platform === 'darwin' ? 'libkrunfw.5.dylib' : 'libkrunfw.so.5';
if (entries.some(name => !['msb', lib, 'libkrunfw.so'].includes(name))) throw new Error('Unexpected runtime archive contents');
execFileSync('tar', ['-xzf', '.cache/runtime.tar.gz', '-C', '.runtime/bin']);
for (const name of entries.filter(name => name.startsWith('libkrunfw'))) await rename(`.runtime/bin/${name}`, `.runtime/lib/${name}`);
console.log(execFileSync('.runtime/bin/msb', ['--version'], { encoding: 'utf8' }).trim());
console.log('Runtime installed separately from existing microsandbox installations.');
