import { collectLeafArtifacts, type ExecutionCheckpoints } from '@multiverse/gameplay-harness';
import type { WorldRuntime } from './runtime.ts';

/** References are generated by this application and never accepted from the browser. */
export type CheckpointAdapter = ExecutionCheckpoints<WorldRuntime>;

type IndexedSnapshot = { id: string; digest: string; parentDigest: string | null; group: string | null; name: string | null; reference: string };
/** Delete only requested leaves. Ancestors of retained snapshots remain queued. */
export async function collectCheckpointSnapshots(references: string[], inventory: IndexedSnapshot[], remove: (reference: string) => Promise<void>): Promise<string[]> {
  return collectLeafArtifacts(references, inventory.map(snapshot => ({
    key: snapshot.group !== null && snapshot.name !== null ? `${snapshot.group}:${snapshot.name}` : snapshot.reference,
    identities: [snapshot.id, snapshot.digest],
    dependencies: snapshot.parentDigest ? [snapshot.parentDigest] : [],
    value: snapshot.reference,
  })), remove);
}
export const checkpoints: CheckpointAdapter = {
  async capture(world, reference) {
    if (!world.captureCheckpoint) throw new Error('Runtime does not support execution checkpoints');
    await world.captureCheckpoint(reference);
  },
  async restore(reference, id) {
    const { restoreCheckpoint } = await import('./runtime.ts');
    return restoreCheckpoint(reference, id);
  },
  async collect(references) {
    const { Snapshot } = await import('microsandbox');
    return collectCheckpointSnapshots(references, await Snapshot.list(), reference => Snapshot.remove(reference));
  },
  async remove(reference) {
    const { Snapshot } = await import('microsandbox');
    // Absence makes cleanup idempotent; other failures must remain visible.
    const existing = await Snapshot.list();
    const [group, member] = reference.split(':');
    const match = existing.find(s => s.group === group && s.name === member);
    if (match) await Snapshot.remove(reference);
  },
};
